# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LATlO0pWLuQHYE0W7nFaVqHb2DwAgwTF
"""

"""
Generator dataset sentimen Bahasa Indonesia.
Menghasilkan review bervariasi (e-commerce, aplikasi, makanan, film, layanan)
dengan kombinasi template + frasa, lalu menyimpan ke data.csv.
"""
import csv
import random

random.seed(42)

# ---------- KOMPONEN POSITIF ----------
pos_subjects = [
    "barangnya", "produknya", "kualitasnya", "pelayanannya", "pengirimannya",
    "aplikasinya", "makanannya", "filmnya", "tempatnya", "harganya",
    "respon sellernya", "packingnya", "fiturnya", "rasanya", "desainnya",
]
pos_adjectives = [
    "bagus banget", "mantap", "memuaskan", "keren", "sesuai ekspektasi",
    "cepat", "ramah", "berkualitas", "worth it", "recommended",
    "enak sekali", "rapi", "lengkap", "nyaman", "luar biasa",
    "melebihi harapan", "top markotop", "oke punya", "joss", "sangat membantu",
]
pos_closers = [
    "pokoknya puas", "terima kasih banyak", "bakal beli lagi",
    "recommended seller", "sangat direkomendasikan", "lanjutkan",
    "semoga makin sukses", "tidak menyesal beli", "the best", "puas banget",
    "akan langganan", "mantap jiwa", "five stars", "suka sekali", "",
]
pos_full = [
    "barang sesuai deskripsi pengiriman cepat seller ramah recommended",
    "kualitas produk sangat bagus harga terjangkau pelayanan memuaskan",
    "aplikasinya mudah digunakan fiturnya lengkap dan tidak ngelag",
    "makanannya enak porsinya banyak tempatnya bersih pelayanan cepat",
    "filmnya seru alur cerita menarik akting pemainnya memukau",
    "pengiriman super cepat packing aman barang mulus tanpa cacat",
    "saya sangat puas dengan produk ini kualitasnya melebihi harga",
    "respon penjual ramah cepat tanggap proses order lancar sekali",
    "produk original sesuai gambar awet dan nyaman dipakai sehari hari",
    "tempat makannya cozy harganya ramah di kantong rasanya juara",
    "barang cepat sampai kualitas oke banget bakal order lagi nanti",
    "pelayanan toko sangat profesional dan memuaskan tidak mengecewakan",
    "aplikasi ringan tidak boros baterai tampilan modern enak dilihat",
    "kursusnya jelas materinya lengkap pengajarnya sabar sangat membantu",
    "hotelnya bersih staf ramah lokasi strategis pemandangan indah",
]

# ---------- KOMPONEN NEGATIF ----------
neg_subjects = pos_subjects
neg_adjectives = [
    "jelek banget", "mengecewakan", "buruk", "lambat", "tidak sesuai",
    "murahan", "rusak", "lemot", "hambar", "mahal tidak sebanding",
    "kasar", "berantakan", "membosankan", "tidak ramah", "parah",
    "tidak original", "cacat", "error terus", "lama banget", "menyebalkan",
]
neg_closers = [
    "sangat kecewa", "tidak rekomen", "kapok beli di sini", "jangan beli",
    "buang buang uang", "menyesal sekali", "tidak akan kembali lagi",
    "pelayanan perlu diperbaiki", "sangat mengecewakan", "rugi besar",
    "tidak sesuai harapan", "bikin kesal", "zonk", "minta refund", "",
]
neg_full = [
    "barang tidak sesuai gambar kualitas buruk pengiriman lama sekali",
    "produk datang dalam keadaan rusak seller tidak mau bertanggung jawab",
    "aplikasinya sering error lemot dan boros baterai sangat mengganggu",
    "makanannya hambar porsi sedikit harga mahal pelayanan lambat",
    "filmnya membosankan alur berantakan akting kaku buang buang waktu",
    "pengiriman molor seminggu packing asal asalan barang penyok",
    "saya kecewa berat produk palsu tidak sesuai deskripsi sama sekali",
    "respon penjual lambat jutek tidak membantu proses ribet sekali",
    "barang cacat tidak bisa dipakai minta tukar malah dipersulit",
    "tempat makan kotor pelayan tidak ramah harga tidak masuk akal",
    "aplikasi berat sering force close data hilang sangat menyebalkan",
    "kursusnya membingungkan materi tidak lengkap pengajar tidak jelas",
    "hotel kotor kamar bau ac rusak staf cuek pelayanan mengecewakan",
    "produk tidak awet baru sebentar sudah rusak kualitas murahan",
    "pengiriman salah alamat customer service tidak responsif parah",
]

NEG_PREFIX = ["sayang sekali", "sayangnya", "kecewa karena", "buruknya",
              "masalahnya", "parahnya", ""]
POS_PREFIX = ["alhamdulillah", "senang sekali", "puas karena", "untungnya",
              "mantapnya", "asyiknya", ""]


def gen_template(subjects, adjectives, closers, prefixes):
    subj = random.sample(subjects, k=random.randint(1, 2))
    parts = []
    pre = random.choice(prefixes)
    if pre:
        parts.append(pre)
    for s in subj:
        parts.append(f"{s} {random.choice(adjectives)}")
    closer = random.choice(closers)
    if closer:
        parts.append(closer)
    return " ".join(parts)


def build(n_per_class=1500):
    rows = []
    for _ in range(n_per_class):
        # variasi: sebagian dari template, sebagian dari kalimat penuh
        if random.random() < 0.6:
            rows.append((gen_template(pos_subjects, pos_adjectives, pos_closers, POS_PREFIX), 1))
        else:
            rows.append((random.choice(pos_full), 1))

        if random.random() < 0.6:
            rows.append((gen_template(neg_subjects, neg_adjectives, neg_closers, NEG_PREFIX), 0))
        else:
            rows.append((random.choice(neg_full), 0))

    random.shuffle(rows)
    # dedup ringan
    seen = set()
    final = []
    for text, label in rows:
        key = text
        if key in seen:
            continue
        seen.add(key)
        final.append((text, label))
    return final


def main():
    rows = build(n_per_class=3500)
    with open("data.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        w.writerows(rows)
    pos = sum(1 for _, l in rows if l == 1)
    neg = len(rows) - pos
    print(f"data.csv dibuat: {len(rows)} baris (positif={pos}, negatif={neg})")


if __name__ == "__main__":
    main()

