# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vF8GjIhvtmNJMa4MJqgWYs-nmwevaXRj
"""

"""
Modul preprocessing bersama (dipakai train.py, app Flask, dan Streamlit).
Pastikan logika cleaning identik di training & inference.
"""
import re
import string

try:
    from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
    from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
    _stemmer = StemmerFactory().create_stemmer()
    _stopwords = set(StopWordRemoverFactory().get_stop_words())
    USE_SASTRAWI = True
except Exception:
    USE_SASTRAWI = False
    _stemmer = None
    _stopwords = set("""
        yang di ke dari dan atau ini itu untuk dengan pada adalah ada akan
        saya kamu dia kami kita mereka aku anda nya tak tidak bukan juga saja
        sudah belum masih bisa harus mau ingin agar supaya karena sebab maka
        sehingga namun tetapi tapi sangat lebih paling akan telah pun lah kah
    """.split())


def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"@\w+|#\w+", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def preprocess(text):
    text = clean_text(text)
    tokens = text.split()
    tokens = [t for t in tokens if t not in _stopwords and len(t) > 2]
    if USE_SASTRAWI:
        tokens = [_stemmer.stem(t) for t in tokens]
    return " ".join(tokens)